package Vista;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


import Controlador.Inventario;
import Modelo.Producto;
import javax.swing.JOptionPane;

/**
 *
 * @author Akerux
 */
public class Menu_actualizarProd extends javax.swing.JFrame {
    
    
    Inventario inv = new Inventario();
    /**
     * Creates new form Menu_actualizarProd
     */
    public Menu_actualizarProd() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtext_nomProd_Update = new javax.swing.JTextField();
        jtext_precio_Update = new javax.swing.JTextField();
        jtext_stock_Update = new javax.swing.JTextField();
        jcomb_tipoProd_update = new javax.swing.JComboBox<>();
        jbutt_ActualizarProd_Update = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jbutt_buscarID = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jtext_IdProd_Update = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Actualizar Datos Del Producto"));

        jLabel3.setText("Stock");

        jLabel4.setText("Precio");

        jLabel5.setText("Nombre Producto");

        jLabel6.setText("Tipo De Producto");

        jtext_nomProd_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtext_nomProd_UpdateActionPerformed(evt);
            }
        });

        jcomb_tipoProd_update.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Producto general", "Bebidas", "Vino", "Destilados" }));

        jbutt_ActualizarProd_Update.setText("Actulizar");
        jbutt_ActualizarProd_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutt_ActualizarProd_UpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jtext_stock_Update, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                        .addComponent(jtext_precio_Update))
                    .addComponent(jtext_nomProd_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcomb_tipoProd_update, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbutt_ActualizarProd_Update)
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtext_nomProd_Update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtext_precio_Update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtext_stock_Update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jcomb_tipoProd_update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jbutt_ActualizarProd_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar por ID "));

        jbutt_buscarID.setText("Buscar");
        jbutt_buscarID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutt_buscarIDActionPerformed(evt);
            }
        });

        jLabel2.setText("ID Producto");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtext_IdProd_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbutt_buscarID)
                .addGap(28, 28, 28))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbutt_buscarID)
                    .addComponent(jLabel2)
                    .addComponent(jtext_IdProd_Update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtext_nomProd_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtext_nomProd_UpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtext_nomProd_UpdateActionPerformed

    private void jbutt_ActualizarProd_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutt_ActualizarProd_UpdateActionPerformed
       
       int selectedItem; // Busca los items que estan en tipo producto
       int idProducto, stock, precioProducto;
       String nombreProducto, tipoProducto;
   
       selectedItem = jcomb_tipoProd_update.getSelectedIndex();
       tipoProducto = this.jcomb_tipoProd_update.getItemAt(selectedItem);
        
       idProducto = Integer.parseInt(this.jtext_IdProd_Update.getText());
       nombreProducto = this.jtext_nomProd_Update.getText();
       precioProducto = Integer.parseInt(this.jtext_precio_Update.getText());
       stock = Integer.parseInt(this.jtext_stock_Update.getText());
       
       Producto prod = new Producto(idProducto, stock, precioProducto, nombreProducto, tipoProducto);
       
       inv.actualizarProducto(prod);
       JOptionPane.showMessageDialog(null , "Producto actualizado!!!" , "Actualizar", 1);
        
    }//GEN-LAST:event_jbutt_ActualizarProd_UpdateActionPerformed

    private void jbutt_buscarIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutt_buscarIDActionPerformed

        Inventario inventario = new Inventario();
        
        int id = Integer.parseInt(this.jtext_IdProd_Update.getText());
        Producto producto = inventario.buscarIdProducto(id);
        
        //rescato los datos del objeto libro
        String nombreProducto = producto.getNombreProducto();
        int precioProducto = producto.getPrecioProducto();
        int stock = producto.getStock();
        String tipoProducto = producto.getTipoProducto();   
                
        //pasar estas variables anteriores a los textos de cada texfield de la ventana
        this.jtext_nomProd_Update.setText(nombreProducto);
        this.jtext_precio_Update.setText(String.valueOf(precioProducto));
        this.jtext_stock_Update.setText(String.valueOf(stock));
        this.jcomb_tipoProd_update.setSelectedItem(tipoProducto); // hace un nuevo set de item de la combo box

          
    }//GEN-LAST:event_jbutt_buscarIDActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbutt_ActualizarProd_Update;
    private javax.swing.JButton jbutt_buscarID;
    private javax.swing.JComboBox<String> jcomb_tipoProd_update;
    private javax.swing.JTextField jtext_IdProd_Update;
    private javax.swing.JTextField jtext_nomProd_Update;
    private javax.swing.JTextField jtext_precio_Update;
    private javax.swing.JTextField jtext_stock_Update;
    // End of variables declaration//GEN-END:variables
}
