package Vista;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


import Controlador.Inventario;
import javax.swing.JOptionPane;

/**
 *
 * @author Akerux
 */
public class Menu_Eliminar extends javax.swing.JFrame {

    /**
     * Creates new form Menu_Eliminar
     */
    public Menu_Eliminar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jbutt_Eliminar = new javax.swing.JButton();
        jtext_id_eliminar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(246, 236, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Eliminar Producto"));

        jLabel1.setText("ID Producto");

        jbutt_Eliminar.setText("Eliminar");
        jbutt_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutt_EliminarActionPerformed(evt);
            }
        });

        jtext_id_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtext_id_eliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtext_id_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbutt_Eliminar)
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jbutt_Eliminar)
                    .addComponent(jtext_id_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbutt_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutt_EliminarActionPerformed
        
        int idProducto;
        
        idProducto = Integer.parseInt(this.jtext_id_eliminar.getText());
        
        Inventario inv = new Inventario();
        
        int opc = JOptionPane.showConfirmDialog(null,"Seguro que desea eliminar el producto","Eliminar",0);
        
        if (opc == 0) 
        {
            inv.eliminarProducto(idProducto);
            JOptionPane.showMessageDialog(null, "Producto Eliminado con exito" , "Eliminar" , 1);
        }else
        {
            JOptionPane.showMessageDialog(null, "Producto no se ha Eliminado" , "Eliminar" , 2);
        }
        
    }//GEN-LAST:event_jbutt_EliminarActionPerformed

    private void jtext_id_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtext_id_eliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtext_id_eliminarActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbutt_Eliminar;
    private javax.swing.JTextField jtext_id_eliminar;
    // End of variables declaration//GEN-END:variables
}
